# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

jobs:
  # run tests
  test:
    docker:
      - image: circleci/node:12.18.4
      - image: circleci/mongo:4.4
    working_directory: ~/api
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - run: npm rebuild
      # cache node modules
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm test

orbs:
  gcp-gke: circleci/gcp-gke@1.1.0

version: 2.1

workflows:
  test_build_deploy:
    jobs:
      - test
      # The build step is now in the Dockerfile
      # Since it's an Orb job I did not find a way to use a cached version of the
      # built app from a previous job like we do in `config.kops.yml`
      - gcp-gke/publish-and-rollout-image:
          context:
            - GKE
          cluster: experimental-cluster
          container: nas
          deployment: node-api-starter
          google-compute-zone: GKE_COMPUTE_ZONE
          image: gcr.io/unique-serenity-287315/feredean/node-api-starter
          tag: $CIRCLE_SHA1
          requires:
            - test
          # filters:
          #   # only deploy when a commit hits the master branch
          #   branches:
          #     only: master
