# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  
  build:
    docker:
      - image: circleci/node:12.6.0
      - image: circleci/mongo:3.4.4
    working_directory: ~/api

    steps:
      - checkout
      - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - run: npm rebuild
      - save_cache:
        paths:
          - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test

  deploy:
    machine: true
    working_directory: ~/api
    steps:
      - checkout
      - run:    
        name: Deploy to private docker registry
        # TAG to be used when kubernetes is implemented
        command: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t <docker image name> .
          docker login <docker registry> -u $DOCKER_USER -p $DOCKER_PASS
          docker push <docker image name>

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
