apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-api-starter
spec:
  replicas: 1
  revisionHistoryLimit: 4
  selector:
    matchLabels:
      app: node-api-starter
      category: open-source
  template:
    metadata:
      labels:
        app: node-api-starter
        category: open-source
    spec:
      containers:
        - name: nas
          image: gcr.io/unique-serenity-287315/feredean/node-api-starter
          imagePullPolicy: Always
          ports:
            - containerPort: 9100
          envFrom:
            - secretRef:
                name: gcr-secret
